name: Build iOS Simulator App

on:
  workflow_dispatch:
  push:
    branches: [ main ]  # Change to 'mobile' if you want your mobile branch

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm ci

      - name: Build React project
        run: npm run build

      - name: Sync Capacitor iOS
        run: |
          npm install @capacitor/cli @capacitor/core --no-save
          npm install @capacitor/ios --no-save
          npx cap sync ios

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Build iOS Simulator .app
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphonesimulator -derivedDataPath build

      - name: Zip the .app
        run: |
          cd ios/App/build/Build/Products/Release-iphonesimulator
          zip -r app-simulator.zip *.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-simulator-app
          path: ios/App/build/Build/Products/Release-iphonesimulator/app-simulator.zip
